const categories = [
  "🌼🐣 Easter Holiday 🐣🌼",
  "🍃🌸 Spring Sale 🌸🍃",
  "🏅 Top Sales 🏅",
  "✅ Child Panel",
  "✅ Exclusive Instagram Italian Services",
  "✅ TikTok Followers",
  "✅ TikTok Likes / Shares / Saves",
  "✅ TikTok Comments",
  "✅ TikTok Views",
  "✅ TikTok Auto Services",
  "✅ Twitch",
  "✅ Facebook Page Likes",
  "✅ Facebook Post Likes",
  "✅ Facebook Emoticons",
  "✅ Facebook Comments & Comment Likes",
  "✅ Facebook Reviews/Rating",
  "✅ Facebook Video Views",
  "✅ Facebook Live Video Views",
  "✅ Facebook Others",
  "✅ Instagram Followers [ Refill ]",
  "✅ Instagram Followers [ Country Targeted ]",
  "✅ Instagram Followers [ Gender ]",
  "✅ Instagram Likes",
  "✅ Instagram Likes [ Targeted ]",
  "✅ Instagram Views / Story Views",
  "✅ Instagram AUTO Services",
  "✅ Instagram Live Video [ Views / Likes / Comments ]",
  "✅ Instagram Power Comments",
  "✅ Instagram Comments / Comment Likes",
  "✅ Instagram Verified Comments",
  "✅ Instagram Mentions / Direct Message",
  "✅ Instagram Impressions & Saves",
  "✅ IGTV",
  "✅ Instagram Packages",
  "✅ YouTube Shorts [ Views / Likes ]",
  "✅ YouTube Views [ Worldwide - Refill ]",
  "✅ YouTube Views [ Monetizable / Organic / ADS ]",
  "✅ YouTube Suggested [ Views from related videos ]",
  "✅ YouTube Auto Services",
  "✅ YouTube Livestream [ Views / Likes ]",
  "✅ YouTube Subscribers",
  "✅ YouTube Likes / Dislikes",
  "✅ YouTube Comments / Comment Likes / Comment DisLikes",
  "✅ YouTube Shares [ Country Targeted ]",
  "✅ Likee",
  "✅ Twitter Followers",
  "✅ Twitter Likes / Favorites / Views",
  "✅ Twitter Retweets",
  "✅ Twitter Poll Votes",
  "✅ Twitter Comments",
  "✅ Twitter Others",
  "✅ Spotify Extra",
  "✅ Spotify Plays [ Targeted ]",
  "✅ Spotify Premium Plays [ Targeted ]",
  "✅ Spotify Plays [ Language Targeted ]",
  "✅ Spotify",
  "✅ Spotify Followers",
  "✅ Spotify Package",
  "✅ Mixcloud",
  "✅ Linkedin",
  "✅ Music Plays",
  "✅ SoundCloud",
  "✅ Discord Services",
  "✅ Deezer Followers",
  "✅ Discord Services [ Targeted ]",
  "✅ Reddit",
  "✅ Quora Votes",
  "✅ Quora",
  "✅ Reverbnation",
  "✅ Telegram",
  "✅ Telegram Post Views [S2]",
  "✅ Telegram Reactions",
  "✅ Vimeo",
  "✅ Pinterest",
  "✅ Dailymotion",
  "✅ iOS App Rating / Reviews",
  "✅ App Promotion [ iOS / Android ]",
  "✅ Android App Installs",
  "✅ Press Release Writing and Distribution",
  "✅ SEO Services - Google Rankings",
  "✅ SEO Packages",
  "✅ SEO Packages [ Drip-Feed ]",
  "✅ CHEAP SEO Packages [ Monthly]",
  "✅ Ranking Articles",
  "✅ Website Traffic [Custom Keywords]",
  "✅Worldwide Traffic",
  "✅GEO Targeted Traffic",
  "✅Mobile Traffic",
  "✅Exchange Platforms Traffic (PTC)",
  "✅ Website Traffic from iPhone",
  "✅ Website Traffic from Japan",
  "✅ Website Traffic from China",
  "✅ Website Traffic from India",
  "✅PRIVATE",
];

export default categories;
